DROP SEQUENCE if exists PUBLIC.USERS_ID_SEQ;

CREATE SEQUENCE PUBLIC.USERS_ID_SEQ
  MINVALUE 1000000
  MAXVALUE 9999999999999999
  START WITH 1000000
  INCREMENT BY 100
  CACHE 100;

create table DB_USERS(
      username varchar_ignorecase(50) not null ,
      password varchar_ignorecase(500) not null,
      active boolean not null,
      userid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL ,
      name varchar_ignorecase(128) not null,
      surname varchar_ignorecase(128) not null,
      email varchar_ignorecase(128) not null,
      confirmationtoken varchar_ignorecase(128),
      createdate datetime not null
      );

      
DROP SEQUENCE if exists PUBLIC.AUTH_ID_SEQ;

CREATE SEQUENCE PUBLIC.AUTH_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;
      
create table DB_AUTHORITIES (
      authid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL ,
      username varchar_ignorecase(50) not null,
      authority varchar_ignorecase(128) not null);

create unique index idx_auth_username on db_authorities (username,authority);

create table DB_IMAGES(
      id int GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) NOT NULL ,
      imagetype varchar_ignorecase(128) not null,
      name varchar_ignorecase(128) not null,
      data BLOB
      );

