DROP SEQUENCE if exists users_userid_SEQ;

CREATE SEQUENCE users_userid_SEQ
  MINVALUE 100
  MAXVALUE 9999999999999999
  START WITH 100
  INCREMENT BY 100
  CACHE 100;

create table users(
      userid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL ,
      username varchar_ignorecase(128) not null ,
      password varchar_ignorecase(512) not null,
      firstname varchar_ignorecase(128) not null,
      lastname varchar_ignorecase(128) not null,
      email varchar_ignorecase(128) not null,
      confirmationtoken varchar_ignorecase(128),
      enabled boolean not null);
      
      
create table authorities (
      userid varchar_ignorecase(128) not null,
      authority varchar_ignorecase(128) not null);

create unique index idx_auth_username on authorities (userid,authority);

