logging.file: logs/springbootmywebapp.log 
logging:
  level:
    org.springframework.web: error
    org.springframework.boot: error
    org.springframework.core: error
    org.springframework.beans: error
    org.springframework.webapp: error
    org.springframework.security: error
    org.springframework.jdbc.datasource: trace
    org.springframework.jdbc.core : trace
    web: error
  file: 
    max-history: 20
    max-size: 50MB  pattern:     console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 